# arrivals histogram
# [X, Y] means P(in 0 jobs) = X; P(in 1 jobs) = Y
arrivals_histogram:
  - 0.5
  - 0.5


# departures histogram
# [X, Y] means P(out 0 jobs) = X; P(out 1 jobs) = Y
departures_histogram:
  - 0.
  - 1.

# queue size is the max number of jobs waiting in the queue
queue_size: 2

# server max cap represent the max cap of servers allocated in the slice
server_max_cap: 2

# alpha is a parameter responsible for the cost normalization [job in queue]
alpha: 1

# beta is a parameter responsible for the cost normalization [server]
beta: 1

# gamma is a parameter responsible for the cost normalization [lost]
gamma: 1

# c server is the cost to have a vm turned on in a time slot
c_server: 1

# c job is the cost to have a job in the queue in a time slot
c_job: 1

# c lost is the cost to lost a job due to queue full
c_lost: 1

# simulations represent the number of sim to be done in order to get the average for the plots
simulations: 1

# simulation time (in timeslots) indicates timing for each simulation done
simulation_time: 1000

# mdp discount start value indicates the default value for the discount discovery routine
mdp_discount_start_value: 1.

# mdp discount end value indicates the end value for the discount discovery routine
mdp_discount_end_value: 1.

# mdp discount increment represent the delta used for the discount discovery routine
mdp_discount_increment: 0.1

# mdp algo is useful to impose a specific algorithm for the policy calculation in mdp
# available: 'vi' for value iteration; 'fh' for finite horizon
mdp_algorithm: vi

# delayed action effect the behaviour of the mdp formulation and of the simulator too
delayed_action: False

# average window in plot is useful when we have plot unreadable due the high number of sample to plot
# this option define the window of the average window technique
average_window_in_plot: 200

# arrival-processing phase is the opposite of processing-arrival phase (exchanged phases)
# if False mdp and simulation will consider the processing phase first and then the arrival phase
arrival_processing_phase: True