immediate_action: True
arrival_processing_phase: True

mdp:
  algorithm: vi
  discount_factor: 0.999

simulation:
  runs: 1
  timeslots: 10

server_max_cap: 2

slices: # Order matter! slice with index 0 is the highest priority ans so on..

  - arrivals_histogram:
      - 0.1
      - 0.9
    server_capacity_histogram:
      - 0.
      - 1.
    queue_size: 2
    alpha: 0.333
    beta: 0.333
    gamma: 0.333
    c_job: 1
    c_server: 1
    c_lost: 1

  - arrivals_histogram:
      - 0.1
      - 0.9
    server_capacity_histogram:
      - 0.
      - 1.
    queue_size: 2
    alpha: 0.333
    beta: 0.333
    gamma: 0.333
    c_job: 10
    c_server: 1
    c_lost: 100