immediate_action: True
arrival_processing_phase: True

mdp:
  algorithm: vi
  discount_factor: 0.999

simulation:
  runs: 1
  timeslots: 10000

server_max_cap: 5

slices:
  - arrivals_histogram: # urllc
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    server_capacity_histogram:
      - 0.3
      - 0.35
      - 0.35
    queue_size: 20
    alpha: 0.333 # TODO: replace this with the old automatic system
    beta: 0.333
    gamma: 0.333
    c_job: 0.000062
    c_server: 0.0001
    c_lost: 0.00062

  - arrivals_histogram: # mtcm
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
      - 0.1
    server_capacity_histogram:
      - 0.3
      - 0.35
      - 0.35
    queue_size: 20
    alpha: 0.333
    beta: 0.333
    gamma: 0.333
    c_job: 0.0000062
    c_server: 0.0001
    c_lost: 0.0000062

  - arrivals_histogram: # emb
      - 0.1
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
      - 0.06
    server_capacity_histogram:
      - 0.3
      - 0.35
      - 0.35
    queue_size: 30
    alpha: 0.333
    beta: 0.333
    gamma: 0.333
    c_job: 0.0000062
    c_server: 0.0001
    c_lost: 0.0000062

