immediate_action: True
arrival_processing_phase: True

mdp:
  algorithm: fh
  discount_factor: 0.999

simulation:
  runs: 5
  timeslots: 1000

server_max_cap: 2

slices: # Order matter! slice with index 0 is the highest priority ans so on..

  - arrivals_histogram:
      - 0.
      - 0.5
      - 0.5
    server_capacity_histogram:
      - 0.
      - 1.
    queue_size: 2
    alpha: 1
    beta: 1
    gamma: 1
    c_job: 1
    c_server: 1
    c_lost: 1

  - arrivals_histogram:
      - 0.
      - 0.4
      - 0.4
      - 0.2
    server_capacity_histogram:
      - 0.
      - 1.
    queue_size: 2
    alpha: 1
    beta: 1
    gamma: 1
    c_job: 1
    c_server: 1
    c_lost: 1